CREATE TABLE user_ai_config (
    user_id BIGINT PRIMARY KEY,
    provider VARCHAR(20) NOT NULL DEFAULT 'deepseek',
    api_key VARCHAR(255) NOT NULL,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户AI配置';
